name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      # TODO: ensure pip is new enough to support dependency groups.
      # TODO: install the project and its dev dependency group.
      # TODO: run the test suite.
      # TODO: run Ruff.
